module.exports = {
  // jobInBuildingStateSchema: require("./jobInBuildingStateSchema"),
  jobCompletedSchema: require("./jobCompletedSchema"),
  // startABuild: require("./startABuildSchema"),
  // abortABuild: require("./abortABuildSchema"),
  // jobanalytics: require("./jobAnalyticsSchema"),
  // eventRecordSchema: require("./eventRecordSchema"),
  // getAllJobOwners: require("./getAllJobOwnersSchema"),
  // jobcommentschema: require("./jobCommentSchema"),
  // listjobs: require("./listjobsSchema"),
  // fetchInprogressSchema: require("./fetchInprogressSchema"),
  // syncjobs: require("./syncjobs"),
  // deleteJobSchema: require("./deleteJobSchema"),
  // reportdashboardSchemas: require("./reportdashboardSchemas"),
};
